name: E2E tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Yarn CLI
      uses: CultureHQ/actions-yarn@v1.0.1
    - name: install
      run: yarn install 
    - uses: docker://circleci/node:8-browsers
    - name: Run e2e tests
      run: yarn run e2e:ci
